# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Varlet MCP Server
FROM node:lts-alpine AS build

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=build /app/dist ./dist
COPY package.json .
RUN npm install --omit=dev --ignore-scripts

# Default command will be set by Smithery startCommand
ENTRYPOINT ["node", "dist/index.js"]
